//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecificationDto", Namespace="http://schemas.datacontract.org/2004/07/MobilePhoneSpecsApi.DTOs")]
    public partial class SpecificationDto : object
    {
        
        private SearchService.GsmBatteryDetailsDto gsmBatteryDetailsField;
        
        private SearchService.GsmBodyDetailsDto gsmBodyDetailsField;
        
        private SearchService.GsmDisplayDetailsDto gsmDisplayDetailsField;
        
        private SearchService.GsmLaunchDetailsDto gsmLaunchDetailsField;
        
        private SearchService.GsmMemoryDetailsDto gsmMemoryDetailsField;
        
        private SearchService.GsmSoundDetailsDto gsmSoundDetailsField;
        
        private SearchService.PhoneDetailsDto phoneDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchService.GsmBatteryDetailsDto gsmBatteryDetails
        {
            get
            {
                return this.gsmBatteryDetailsField;
            }
            set
            {
                this.gsmBatteryDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchService.GsmBodyDetailsDto gsmBodyDetails
        {
            get
            {
                return this.gsmBodyDetailsField;
            }
            set
            {
                this.gsmBodyDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchService.GsmDisplayDetailsDto gsmDisplayDetails
        {
            get
            {
                return this.gsmDisplayDetailsField;
            }
            set
            {
                this.gsmDisplayDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchService.GsmLaunchDetailsDto gsmLaunchDetails
        {
            get
            {
                return this.gsmLaunchDetailsField;
            }
            set
            {
                this.gsmLaunchDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchService.GsmMemoryDetailsDto gsmMemoryDetails
        {
            get
            {
                return this.gsmMemoryDetailsField;
            }
            set
            {
                this.gsmMemoryDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchService.GsmSoundDetailsDto gsmSoundDetails
        {
            get
            {
                return this.gsmSoundDetailsField;
            }
            set
            {
                this.gsmSoundDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchService.PhoneDetailsDto phoneDetails
        {
            get
            {
                return this.phoneDetailsField;
            }
            set
            {
                this.phoneDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GsmBatteryDetailsDto", Namespace="http://schemas.datacontract.org/2004/07/MobilePhoneSpecsApi.DTOs")]
    public partial class GsmBatteryDetailsDto : object
    {
        
        private string batteryChargingField;
        
        private string batteryTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string batteryCharging
        {
            get
            {
                return this.batteryChargingField;
            }
            set
            {
                this.batteryChargingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string batteryType
        {
            get
            {
                return this.batteryTypeField;
            }
            set
            {
                this.batteryTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GsmBodyDetailsDto", Namespace="http://schemas.datacontract.org/2004/07/MobilePhoneSpecsApi.DTOs")]
    public partial class GsmBodyDetailsDto : object
    {
        
        private string bodyBuildField;
        
        private string bodyDimensionsField;
        
        private string bodyOther1Field;
        
        private string bodyOther2Field;
        
        private string bodyOther3Field;
        
        private string bodySimField;
        
        private string bodyWeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bodyBuild
        {
            get
            {
                return this.bodyBuildField;
            }
            set
            {
                this.bodyBuildField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bodyDimensions
        {
            get
            {
                return this.bodyDimensionsField;
            }
            set
            {
                this.bodyDimensionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bodyOther1
        {
            get
            {
                return this.bodyOther1Field;
            }
            set
            {
                this.bodyOther1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bodyOther2
        {
            get
            {
                return this.bodyOther2Field;
            }
            set
            {
                this.bodyOther2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bodyOther3
        {
            get
            {
                return this.bodyOther3Field;
            }
            set
            {
                this.bodyOther3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bodySim
        {
            get
            {
                return this.bodySimField;
            }
            set
            {
                this.bodySimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bodyWeight
        {
            get
            {
                return this.bodyWeightField;
            }
            set
            {
                this.bodyWeightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GsmDisplayDetailsDto", Namespace="http://schemas.datacontract.org/2004/07/MobilePhoneSpecsApi.DTOs")]
    public partial class GsmDisplayDetailsDto : object
    {
        
        private string displayOther1Field;
        
        private string displayProtectionField;
        
        private string displayResolutionField;
        
        private string displaySizeField;
        
        private string displayTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string displayOther1
        {
            get
            {
                return this.displayOther1Field;
            }
            set
            {
                this.displayOther1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string displayProtection
        {
            get
            {
                return this.displayProtectionField;
            }
            set
            {
                this.displayProtectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string displayResolution
        {
            get
            {
                return this.displayResolutionField;
            }
            set
            {
                this.displayResolutionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string displaySize
        {
            get
            {
                return this.displaySizeField;
            }
            set
            {
                this.displaySizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string displayType
        {
            get
            {
                return this.displayTypeField;
            }
            set
            {
                this.displayTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GsmLaunchDetailsDto", Namespace="http://schemas.datacontract.org/2004/07/MobilePhoneSpecsApi.DTOs")]
    public partial class GsmLaunchDetailsDto : object
    {
        
        private string launchAnnouncedField;
        
        private string launchStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string launchAnnounced
        {
            get
            {
                return this.launchAnnouncedField;
            }
            set
            {
                this.launchAnnouncedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string launchStatus
        {
            get
            {
                return this.launchStatusField;
            }
            set
            {
                this.launchStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GsmMemoryDetailsDto", Namespace="http://schemas.datacontract.org/2004/07/MobilePhoneSpecsApi.DTOs")]
    public partial class GsmMemoryDetailsDto : object
    {
        
        private string memoryCardSlotField;
        
        private string memoryInternalField;
        
        private string memoryOther1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memoryCardSlot
        {
            get
            {
                return this.memoryCardSlotField;
            }
            set
            {
                this.memoryCardSlotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memoryInternal
        {
            get
            {
                return this.memoryInternalField;
            }
            set
            {
                this.memoryInternalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memoryOther1
        {
            get
            {
                return this.memoryOther1Field;
            }
            set
            {
                this.memoryOther1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GsmSoundDetailsDto", Namespace="http://schemas.datacontract.org/2004/07/MobilePhoneSpecsApi.DTOs")]
    public partial class GsmSoundDetailsDto : object
    {
        
        private string sound35MmJackField;
        
        private string soundLoudspeakerField;
        
        private string soundOther1Field;
        
        private string soundOther2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sound35MmJack
        {
            get
            {
                return this.sound35MmJackField;
            }
            set
            {
                this.sound35MmJackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soundLoudspeaker
        {
            get
            {
                return this.soundLoudspeakerField;
            }
            set
            {
                this.soundLoudspeakerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soundOther1
        {
            get
            {
                return this.soundOther1Field;
            }
            set
            {
                this.soundOther1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soundOther2
        {
            get
            {
                return this.soundOther2Field;
            }
            set
            {
                this.soundOther2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneDetailsDto", Namespace="http://schemas.datacontract.org/2004/07/MobilePhoneSpecsApi.DTOs")]
    public partial class PhoneDetailsDto : object
    {
        
        private string brandValueField;
        
        private string modelValueField;
        
        private string yearValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brandValue
        {
            get
            {
                return this.brandValueField;
            }
            set
            {
                this.brandValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelValue
        {
            get
            {
                return this.modelValueField;
            }
            set
            {
                this.modelValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yearValue
        {
            get
            {
                return this.yearValueField;
            }
            set
            {
                this.yearValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchService.ISearchService")]
    public interface ISearchService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Search", ReplyAction="http://tempuri.org/ISearchService/SearchResponse")]
        System.Threading.Tasks.Task<SearchService.SpecificationDto[]> SearchAsync(string query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISearchServiceChannel : SearchService.ISearchService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SearchServiceClient : System.ServiceModel.ClientBase<SearchService.ISearchService>, SearchService.ISearchService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SearchServiceClient() : 
                base(SearchServiceClient.GetDefaultBinding(), SearchServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISearchService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SearchServiceClient.GetBindingForEndpoint(endpointConfiguration), SearchServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SearchServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SearchServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SearchService.SpecificationDto[]> SearchAsync(string query)
        {
            return base.Channel.SearchAsync(query);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISearchService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISearchService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5095/SpecificationSearchService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SearchServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISearchService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SearchServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISearchService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISearchService,
        }
    }
}
